In [4]:
# vd1: Tạo mảng numpy 1 chiều từ 0 -> 9
import numpy as np
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
# vd2: Tạo 1 mảng boolean 2*3 với tất cả giá tị là TRUE
import numpy as np
# C1: 
arr1 = np.ones((2,3)) > 0
print("Method1:")
print(arr1) 
# C2:
arr2 = np.ones((2,3), dtype = bool)
print("Method2:")
print(arr2)
# C3:
arr3 = np.full((2,3), True, dtype = bool)
print("Method3:")
print(arr3)

Method1:
[[ True  True  True]
 [ True  True  True]]
Method2:
[[ True  True  True]
 [ True  True  True]]
Method3:
[[ True  True  True]
 [ True  True  True]]


In [6]:
# vd3: Lấy những phần tử mà thỏa mãn 1 dk cho trước của mảng 1 chiều. Cho mảng 1 chều có giá trị từ 0 -> 9
# 1: TÌm phần tử có giá trị lẻ
# 2: Tìm phần tử có giá trị chẵn
import numpy as np
# c1
a = np.arange(1,10)
a_oll = a[a%2==1]
print(a_oll)
# c2:
a = [ i for i in range(10) if i%2==1]
print(a) 
b = np.arange(1,10)
b_oll = b[b%2==0]
print(b_oll)
b = [j for j in range(10) if j%2==0]
print(b)

[1 3 5 7 9]
[1, 3, 5, 7, 9]
[2 4 6 8]
[0, 2, 4, 6, 8]


In [7]:
# vd4: Thay thế phần tử thỏa mãn dk cho trc bằng 1 giá trị khác. Cho mảng 1 chiều có giá trị từ 0->9 , thay thế phần tử có giá trị lẻ =10
import numpy as np
a = np.arange(10)
a[a%2==1] = 10
print(a)


[ 0 10  2 10  4 10  6 10  8 10]


In [8]:
# vd5: Thay thế phần tử thỏa mãn điều kiện cho trc bằng 1 giá trị # . cho 1 mảng thay thế tất
# cả sô chẵn bằng giá trị 11 nhưng mảng ban đầu không thay đổi\
import numpy as np
a = np.arange(10)
print(a)
out = np.where(a%2==0, 11, a)
print(out)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[11  1 11  3 11  5 11  7 11  9]
[0 1 2 3 4 5 6 7 8 9]


In [9]:
# vd6: Cho mảng 1 chiều từ 0-> 9, chuyển mảng 1 chiều này thành mamgr 2 chiều có 2 hàng
import numpy as np
# tạo mảng 1d gồm 10 phần tử
a = np.arange(10)
print(a)
# -1 có ý nghĩa là sô cột của a_2d được tính tự động
a_2d = a.reshape(2,-1)
print(a_2d)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
# vd7: cho 2 mảng ( Xếp chồng 2 mảng theo chiều dọc)
a1 = np.arange(10).reshape(2,-1)
a2 = np.arange(10,0,-1).reshape(2,-1)
# c1: 
out1 = np.concatenate([a1,a2],axis = 0)
print(out1)
# c2: 
out2 = np.vstack([a1,a2])
print(out2)
# c3:
out3 = np.r_[a1,a2]
print(out3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [11]:
# vd8: Cho 2 mảng (Xếp chồng 2 mảng theo chiều ngang)
import numpy as np
# Tạo 2 mảng a1 và a2
a1 = np.arange(10).reshape(2,-1)
print(a1)
a2 = np.arange(10,0,-1).reshape(2,-1)
print(a2)
# c1:
out1 = np.concatenate([a1,a2], axis=1)
print(out1)
# c2: 
out2 = np.hstack([a1,a2])
print(out2)
# c3: 
out3 = np.c_[a1,a2]
print(out3)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10  9  8  7  6]
 [ 5  4  3  2  1]]
[[ 0  1  2  3  4 10  9  8  7  6]
 [ 5  6  7  8  9  5  4  3  2  1]]
[[ 0  1  2  3  4 10  9  8  7  6]
 [ 5  6  7  8  9  5  4  3  2  1]]
[[ 0  1  2  3  4 10  9  8  7  6]
 [ 5  6  7  8  9  5  4  3  2  1]]


In [12]:
# vd9: Tạo mảng với các phần tử được lặp từ 1 mảng khác.
import numpy as np
a = np.array([1,2,3])
#c1:
out1 = np.repeat(a,2)
print(out1)
#c2:
out2 = np.tile(a,2)
print(out2)

[1 1 2 2 3 3]
[1 2 3 1 2 3]


In [13]:
#Vd10: Lấy phần tử chung của 2 mảng a1, a2
import numpy as np
a1 = np.array([1,2,3,4,5])
a2 = np.array([3,4,5,6,7])
print(a1)
print(a2)
out = np.intersect1d(a1,a2)
print(out)

[1 2 3 4 5]
[3 4 5 6 7]
[3 4 5]


In [14]:
# vd11: Từ mảng a1 xóa tất cả các phần tử mà có trong mảng a2
import numpy as np
a1 = np.array([2,3,4,5])
a2 = np.array([3,5,9,7])
# Từ mảng a1 xóa tất cả các phần tử mà có trong a=mảng a2
out = np.setdiff1d(a1,a2)
print(out)

[2 4]


In [15]:
# vd12: Lấy tất cả vị trí mà các phần tử có giá trị giống nhau
import numpy as np
a1 = np.array([3,4,5,6,7,8])
a2 = np.array([3,3,6,6,7,7])
index  = np.where(a1 == a2)
print(index)
print(index[0])

(array([0, 3, 4], dtype=int64),)
[0 3 4]


In [16]:
# vd13: Tìm tất cả vị trí và giá trị của các phần tử có giá trị trong phạm vi cho trước
import numpy as np
a = np.array([1,7,3,9,4,7])
print(a)
# C1
index1 = np.where((a>=4) & (a<=8))
out1 = a[index1]
print(out1)
#c2
index2 = np.where(np.logical_and(a>=4, a<=8))
out2 = a[index2]
print(out2)
# c3: 
out3 = a[(a>=4) & (a<=8)]
print(out3)

[1 7 3 9 4 7]
[7 4 7]
[7 4 7]
[7 4 7]


In [17]:
# vd14: Tìm giá trị max giữa 2 mảng
import numpy as np
a1 = np.array([4,6,2,8,6,9])
a2 = np.array([1,5,4,9,8,5])
# c1: Tạo hàm tìm số lớn hơn trong 2 số
def max_value(x,y):
    if x>=y:
        return x
    else:
        return y

# Dùng numpy.vectorize để áp dụng cho hàm max_value
# otypes là kiểu dữ liệu cho mảng output
pair_max = np.vectorize(max_value, otypes = [int])
out1 = pair_max(a1,a2)
print(out1)
# c2: Dùng hàm maximum
out2 = np.maximum(a1,a2)
print(out2)
# c3: Dùng hàm where
out3 = np.where(a1 > a2, a1, a2)
print(out3)

[4 6 4 9 8 9]
[4 6 4 9 8 9]
[4 6 4 9 8 9]


In [18]:
# vd15: Hoán đổi cột 1 và 2 trong mảng arr
import numpy as np
a = np.arange(12).reshape(4,3)
print(a)
# a có 3 cột, chỉ số index là 0,1,2. Hoán đổi cột 1(index= 0) và cột 2(index = 1)
out = a[:,[1,0,2]]
print(out)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 1  0  2]
 [ 4  3  5]
 [ 7  6  8]
 [10  9 11]]


In [19]:
# vd16: Hoán đổi dòng 1 và 2 trong mảng a
import numpy as np
a = np.arange(12).reshape(4,3)
# a có 4 dòng , chỉ sô index là 0,1,2,3 . Hoán dòng 1 (index = 0) và dòng 2 (index =1)
print(a)
out = a[[1,0,2,3],:]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [20]:
#vd17: Đảo ngược các dòng trong mảng
import numpy as np
a = np.arange(12).reshape(4,3)
print(a)
out = a[::-1]
print(out)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 9 10 11]
 [ 6  7  8]
 [ 3  4  5]
 [ 0  1  2]]


In [21]:
# vd18: Đảo ngược các cột trong mảng 2 chiều
import numpy as np
a = np.arange(12).reshape(4,3)
print(a)
out = a[:,::-1]
print(out)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]


In [22]:
# vd19: sinh ra mangr (2*3) với các số ngẫu nhiên trong khoảng (1,9) và các phàn tử kiểu float
import numpy as np
# Dùng hàm uniform
a = np.random.uniform(1,9, size = (2,3))
print(a)

[[2.66324395 5.4484464  2.79428225]
 [3.19590122 7.4247698  2.63565705]]


In [23]:
# vd20: In mảng 2 chiều kiểu float chỉ với 2 số lẻ
import numpy as np
# Tạo mảng
rand_a = np.random.random([2,3])
print(rand_a)
# giới hạn 2 số lẻ
np.set_printoptions(precision = 2)
print(rand_a)

[[0.88715851 0.31792438 0.22818539]
 [0.0197375  0.6045859  0.89853201]]
[[0.89 0.32 0.23]
 [0.02 0.6  0.9 ]]
