In [1]:
# 1: Tạo mảng numpy( ndarray)
import numpy as np
# tao list
l = list(range(1,4))
# tao ndarray
data = np.array(l)
print(data)
print(data[0])
print(data[1])

[1 2 3]
1
2


In [2]:
# 2: Sử dụng thuộc tính shape và hàm type() cho mảng numpy
import numpy as np
l =list(range(1,4))
data = np.array(l)
print(data)
print(type(data))
print(type(data[0]))
print(data.shape)


[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int32'>
(3,)


In [3]:
# 3: Thay đổi shape của 1 mảng
import numpy as np
arr1 = np.arange(12)
print(arr1.shape)
arr2 = arr1.reshape((3,4))
print(arr2.shape)

(12,)
(3, 4)


In [4]:
import numpy as np
arr1 = np.array([1,2])
print(arr1.dtype)
arr2 = np.array([1.0, 2.0])
print(arr2.dtype)
arr3 = np.array([1,2], dtype=np.int64)
print(arr3.dtype)

int32
float64
int64


In [5]:
# 4: Thay đổi giá trị của 1 phần tử
import numpy as np
# tạo list
l = list(range(1,4))
# tạo ndarray
data = np.array(l)
print(data)
data[0] = 8
print(data)

[1 2 3]
[8 2 3]


In [6]:
# 5: Tạo ndarray với hàm zeros
import numpy as np
# shpae: 2 dòng, 3 cột
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# 6: Tạo ndarray với hàm ones
import numpy as np
# numpy.ones(shape, dtype = None, order = "C")
# shape: 2 dong, 3 cot
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
# 7: Tạo ndarray với hàm full
import numpy as np
# numpy.full(shape, fill_value, dtype = None, order = "C")
# shape: 2 dong, 3 cot
arr = np.full((2,3),9)
print(arr)

[[9 9 9]
 [9 9 9]]


In [11]:
# 8: Tạo ma trận đường chéo
import numpy as np
# nuimpy.eye(N, M=None, k=0, dtype=<class"float">, order = "C")
# shape: 2 dong , 3 cot
arr = np.eye(3)
print(arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# 9: Tạo numpy array với giá trị ngẫu nhiên
import numpy as np
# numpy.random.random(size = None)
# shape: 2 dòng, 3 cột: với phần tử có giá trị ngẫu nhiên
arr = np.random.random((2,3))
print(arr)


[[0.3193574  0.7933697  0.57970367]
 [0.26521142 0.84516228 0.39265406]]


In [14]:
# 10: Điều kiện cho mảng numpy
import numpy as np
arr = np.arange(10)
print(arr)
out = np.where(arr < 5, arr, 10*arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 50 60 70 80 90]


In [15]:
# 11: Chuyển về mảng 1 chiều
import numpy as np
arr = np.array([[1,2],[3,4]])
out = arr.flatten()
print(arr)
print(out)

[[1 2]
 [3 4]]
[1 2 3 4]


In [17]:
# Array Indexing : Numpy cung cấp 1 số cách để truy xuất phần tử trong mảng. Truy xuất phần tử dùng 
# kỹ thuật slicing tương tự như danh sách(list) trong python
# vd1: Lấy các phần tử từ mảng 2 chiều như sau:
import numpy as np
# Khởi tọa numpy aray có shape = (2,3)  có giá trị như sau:
# [[1,2,3]
#  [5,6,7]]
a_array = np.array([[1,2,3],[5,6,7]])
print("A:", a_array)
b_array = a_array[:,1:3]
print(b_array)


A: [[1 2 3]
 [5 6 7]]
[[2 3]
 [6 7]]


In [20]:
# Việc 1 mảng mới được tạo từ slicing sẽ có cùng địa chỉ với mảng gốc. Nếu thay đổi 1 
# trong 2 mảng này thì mảng còn lại cũng thay đổi theo
a_arr = np.array([[1,2,3],[5,6,7]])
print("A:",a_arr)
b_arr = a_arr[:,1:3]
print("B:",b_arr)
print("Before changing: ",a_arr[0,1])
b_arr[0,0] = 99
print("After changing: ",a_arr[0,1])

A: [[1 2 3]
 [5 6 7]]
B: [[2 3]
 [6 7]]
Before changing:  2
After changing:  99


In [21]:
# vd2: Lấy một dòng dữ liệu
import numpy as np
arr = np.array([[1,2,3],[5,6,7],[9,10,11]])
# Hai cách truy cập dữ liệu ở hàng giữa của mảng
# Dùng kết hợp chỉ số và slice -> được array mới có số chiều thấp hơn 
# Nếu chỉ dùng slice ta sẽ có array mới có cùng số chiều với array gốc 

# c1: số chiều giảm
row_r1 = arr[1, :]
# c2: số chiều được giữ nguyên
row_r2 = arr[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[5 6 7] (3,)
[[5 6 7]] (1, 3)


In [22]:
# Vd3: Lấy một cột dữ liệu
import numpy
arr = np.array([[1,2,3],[5,6,7],[9,10,11]])
# c1: số chiều giảm
col_r1 = arr[:,1]
# c2: số chiều được giữ nguyên
col_r2 = arr[:,1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [26]:
# Khi bạn truy xuất mảng dùng slincing, kết quả trả về sễ là mảng con của mảng ban đầu
# Nếu sử dụng chỉ số mảng(index), chúng ta có thể xây dựng mảng tùy ý từng mảng khác
import numpy as np
arr = np.array([[1,2],[3,4],[5,6]])
print(arr)
# Một số ví dụ của truy xuất mảng dùng chỉ số index

# Kết quả thu được là 1 mảng có shape(3,)
print("1:", arr[[0,1,2],[0,1,0]])
# Sẽ thu được kết quả tương đương như tren với cách viết này:
print("2:", np.array([arr[0,0], arr[1,1], arr[2,0]]))
# Khi sử dụng index, bạn được phép truy xuất tới 1 phần tử nhiều hơn 1 lần
print("3:", arr[[0,0],[1,1]])

[[1 2]
 [3 4]
 [5 6]]
1: [1 4 5]
2: [1 4 5]
3: [2 2]


In [27]:
# Boolean Indexing: cho phép chúng ta chọn ra các phần tử tùy ý của 1 mảng. Kiểu truy
# xuất này thường được sử dụng để chọn ra các phần tử thoản mãn dk đó 
import numpy as np
a_arr = np.array([[1,2],[3,4],[5,6]])
print(a_arr)
# Tìm các phần tử lớn hơn 2
# Trả về 1 mảng boolean có sô chiều như mảng a_arr
# và giá trị tại mỗi phần tử là
# True nếu phần tử của a tại đó > 2
# Flase cho trường hơp ngược lại

bool_idx = (a_arr > 2)
print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [28]:
# vd5: Tìm các phần tử thỏa mãn điều kiện và lấy các phần tử tương ứng
import numpy as np
a_array = np.array([[1,2],[3,4],[5,6]])
print(a_arr)

bool_idx = (a_arr > 2)
print("A:",bool_idx)
out = a_arr[bool_idx]
print("B:",out)
print("C:",a_arr[a_arr > 2])

[[1 2]
 [3 4]
 [5 6]]
A: [[False False]
 [ True  True]
 [ True  True]]
B: [3 4 5 6]
C: [3 4 5 6]


In [29]:
# CÁC PHÉP TOÁN TREN MẢNG
# 1: Phép cộng giữa 2 mảng
import numpy as np
x = np.array([1,2,3,4], dtype= np.float64)
y = np.array([5,6,7,8], dtype= np.float64)
print("A:",x)
print("B:",y)
# Tổng của 2 mảng, cả 2 cách cho cùng 1 kết quả
print("C:",x+y)
print("D:",np.add(x,y))

A: [1. 2. 3. 4.]
B: [5. 6. 7. 8.]
C: [ 6.  8. 10. 12.]
D: [ 6.  8. 10. 12.]


In [30]:
# 2: Phép trừ giữa 2 mảng
import numpy as np
x = np.array([1,2,3,4], dtype = np.float64)
y = np.array([5,6,7,8], dtype = np.float64)
print("A:",x)
print("B:",y)
# Hiệu của 2 mảng
print("C:",x-y)
print("D:",np.subtract(x,y))

A: [1. 2. 3. 4.]
B: [5. 6. 7. 8.]
C: [-4. -4. -4. -4.]
D: [-4. -4. -4. -4.]


In [31]:
# 3: Phép nhân giữa 2 mảng
import numpy as np
x = np.array([1,2,3,4], dtype=np.float64)
y = np.array([5,6,7,8], dtype=np.float64)
print("A:",x)
print("B:",y)
# Tính tích từng phần tử của x nhân với từng phần tử của y
print("C:",x*y)
print("D:",np.multiply(x,y))

A: [1. 2. 3. 4.]
B: [5. 6. 7. 8.]
C: [ 5. 12. 21. 32.]
D: [ 5. 12. 21. 32.]


In [33]:
# 4: Phép chia giữa 2 mảng
import numpy as np
x = np.array([1,2,3,4], dtype=np.float64)
y = np.array([5,6,7,8], dtype=np.float64)
print("A:",x)
print("B:",y)
# Phép chia của từng phần tử x  chia với từng phần tử y
print("C:",x/y)
print("D:",np.divide(x,y))

A: [1. 2. 3. 4.]
B: [5. 6. 7. 8.]
C: [0.2        0.33333333 0.42857143 0.5       ]
D: [0.2        0.33333333 0.42857143 0.5       ]


In [34]:
# 5: Tính căn bậc 2 cho từng phần tử
import numpy as np
x = np.array([1,2,3,4], dtype=np.float64)
y = np.array([5,6,7,8], dtype=np.float64)
print("A:",x)
print("B:",y)
# Căn bậc 2 từng phần tử trong x
print("C:",np.sqrt(x))

A: [1. 2. 3. 4.]
B: [5. 6. 7. 8.]
C: [1.         1.41421356 1.73205081 2.        ]


In [35]:
# 6: Phép nhân giữa 2 vector(inner product)
import numpy as np
v = np.array([1,2])
w = np.array([2,3])
# Tính innear product giữa 2 vector
print("A:",v.dot(w))
print("B:",np.dot(v,w))

A: 8
B: 8


In [36]:
# 7: Phép nhân giữa vector và matran
import numpy as np
x = np.array([[1,2],[4,3]])
v = np.array([1,2])
print("A:",x)
print("B:",v)
# Phép nhân giữa ma trận và vector
print("C:",x.dot(v))
print("C:",v.dot(x))
print("C:",np.dot(x,v))
print("C:",np.dot(v,x))

A: [[1 2]
 [4 3]]
B: [1 2]
C: [ 5 10]
C: [9 8]
C: [ 5 10]
C: [9 8]


In [37]:
# 8: Nhân giữa 2 ma trận
import numpy as np
x = np.array([[1,2],[4,3]])
y = np.array([[2,3],[2,1]])

print("A:",x)
print("B:",y)
# phép nhân giữa 2 ma trận
print("c:",x.dot(y))
print("C:",np.dot(x,y))

A: [[1 2]
 [4 3]]
B: [[2 3]
 [2 1]]
c: [[ 6  5]
 [14 15]]
C: [[ 6  5]
 [14 15]]


In [38]:
# 9: Tính tổng cho 1 mảng numpy
import numpy as np
x = np.array([[1,2],[3,4]])
# Tổng các phần tử của mảng
print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

10
[4 6]
[3 7]


In [39]:
# 10: Chuyển vị cho 1 ma trân
import numpy as np
x = np.array([[1,2],[3,4]])
print(x)
# chuyển vị
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [46]:
# Broadcasting: cho phép thực thi các phép toán trên các mảng có kích thước khác nhau
# VD: Chúng ta muốn cộng vector cho 1 hàng của ma tran. chúng ta có thể làm như sau
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x)
# c1: Thếm vector v vào mỗi hàng của ma trận X bằng 1 vòng lặp
for i in range(4):
    y[i, :] = x[i, :]+v

print("A",x)
print("B",v)
print("C",y)

A [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
B [1 0 1]
C [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [47]:
# Cách này hoạt động bt với ma trân X nhỏ. Khi matran X lớn, việc sử dụng vòng lắp
# sẽ rất chậm
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
# Sếp chồng 4 bản sao của v lên nhau
V_t = np.tile(v,(4,1))
# Thực hiện phéo +
Y = x + V_t
print("A:",x)
print("B:",v)
print("C:",V_t)
print("D:",Y)


A: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
B: [1 0 1]
C: [[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
D: [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [48]:
#  Numpy broadcasting cho phép chúng ta thực thi tính toán này mà không cần phải làm thêm các bước thêm vào
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
