In [10]:
# vd1: Đọc tập dữ liệu Iris dùng hàm np.genfromtxt() với dtype = "object". Dữ liệu trả về
# là 1 mảng 2 chiều, với các phần tử có kiểu là byte
import numpy as np
# Cho dtype = 'object', mảng 2 chiều kiêu byte được trả về.
iris = np.genfromtxt("Iris.csv", delimiter=',', dtype = 'object')
print(iris.shape)

# Lấy 1 dòng dữ liệu
a_row = iris[1]
print(a_row)

# In kiểu dữ liệu cho từng phần tử
print(a_row[0], type(a_row[0]))
print(a_row[1], type(a_row[1]))
print(a_row[2], type(a_row[2]))
print(a_row[3], type(a_row[3]))
print(a_row[4], type(a_row[4]))

(151, 6)
[b'1' b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
b'1' <class 'bytes'>
b'5.1' <class 'bytes'>
b'3.5' <class 'bytes'>
b'1.4' <class 'bytes'>
b'0.2' <class 'bytes'>


In [15]:
# vd2: Đọc tập dữ liệu Iris dùng hàm np.genfromtxt() với dtype = None. Dữ liệu trả vể
# về 1 mảng 1 chiều, với các phần tử có kiểu là tuple . Trong mỗi tuple, số kiểu float và chuỗi có kiểu byte
import numpy as np
iris_1d = np.genfromtxt("iris.csv",delimiter=',',dtype = None)
print(iris_1d.shape)

# lấy 1 dòng dữ liệu
a_row = iris_1d[1]
print(a_row)

# In kiểu dữ liệu cho từng phần tử của tuple
print(a_row[0], type(a_row[0]))
print(a_row[1], type(a_row[1]))
print(a_row[2], type(a_row[2]))
print(a_row[3], type(a_row[3]))
print(a_row[4], type(a_row[4]))

(151, 6)
[b'1' b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
b'1' <class 'numpy.bytes_'>
b'5.1' <class 'numpy.bytes_'>
b'3.5' <class 'numpy.bytes_'>
b'1.4' <class 'numpy.bytes_'>
b'0.2' <class 'numpy.bytes_'>


C:\Users\MINH\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:4: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  after removing the cwd from sys.path.


In [16]:
# vd3: Tạo mảng 2 chiều gồm 4 cột dữ liệu đầu tiên
import numpy as np
# Đọc dữ liệu
iris_1d = np.genfromtxt("Iris.csv", delimiter = ',', dtype= None)
# c1: Biến đổi mỗi hàng thành list rồi lấy 4 phần tử đầu
iris_2d_1 = np.array([row.tolist()[:4] for row in iris_1d])
# in 4 dòng đầu tiên
print(iris_2d_1[:4])

# C2: Trích xuất 4 cột đầu khi đọc file dữ liêu, chỉ định dtype="float"
iris_2d_2 = np.genfromtxt("Iris.csv", delimiter = ",", dtype="float", usecols=[0,1,2,3])
# in 4 dòng đầu tiên
print(iris_2d_2[:4])

C:\Users\MINH\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:4: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  after removing the cwd from sys.path.


[[b'Id' b'SepalLengthCm' b'SepalWidthCm' b'PetalLengthCm']
 [b'1' b'5.1' b'3.5' b'1.4']
 [b'2' b'4.9' b'3.0' b'1.4']
 [b'3' b'4.7' b'3.2' b'1.3']]
[[nan nan nan nan]
 [1.  5.1 3.5 1.4]
 [2.  4.9 3.  1.4]
 [3.  4.7 3.2 1.3]]


In [19]:
# vd4: Tìm giá trị trung bình , trung vị, độ lệch chuẩn của cột của tập dữ liệu ( cột thứ 1)
import numpy as np
# Trích xuất cột 1 từ IRIS thành mảng 1 chiều
sepallength = np.genfromtxt("Iris.csv", delimiter = ',', dtype=float, usecols = [0])
print(sepallength.shape)
# Giá trị trung bình, trung vị, độ lệch chuẩn của sepallength
mean, median, std = np.mean(sepallength),np.median(sepallength), np.std(sepallength)
print(mean, median, std)

(151,)
nan nan nan


In [22]:
# vd5: Chuẩn hóa (normalize) cột sepallength để giá trị nằm trong khoảng từ 0 đến 1
import numpy as np
# Trích xuất cột 1 từ IRIS thành mảng 1 chiều
sepallength = np.genfromtxt("iris.csv", delimiter=',',dtype="float",usecols=[0])

# c1: công thức chuẩn hóa 1 mảng có giá trị từ 0 -> 1
# norm_array_a = a(i) - min.a / (max.a-min.a)
norm_sepallength1 = (sepallength - sepallength.min()) / (sepallength.max() - sepallength.min())

# in 5 giá trị đầu tiên
print(norm_sepallength1[:5])
# c2: dùng hàm ptp() lấy phạm vi giá trị tức (max - min)
norm_sepallength2 = (sepallength - sepallength.min()) / sepallength.ptp()

# in 5 giá trị đầu tiên
print(norm_sepallength2[:5])

[nan nan nan nan nan]
[nan nan nan nan nan]


In [ ]:
#vd6: Tính softmax cho cột sepallength
import numpy as np
# Trích xuát cột 1 từ IRis thành mảng 1 chiều
sepallength = np.genfromtxt("Iris.csv", delimiter=',',dtype="float", usecols=[0])
print(sepallength.shape)

def softmax(x):
    # Tính giá trị softmax cho từng phần tử của x
    e_x = np.exp(x - np.max(x))
    return e_x/e_x.sum()
# in chỉ 3 số lẻ
np.set_printoptions(precision=4)
print(softmax(sepallength))

In [ ]:
# vd7: Đọc tập dữ liệu Iris dùng hàm np.genfromtxt() với dtype = "float". Dữ liệu trả về là 1 mảng
# 2 chiều , với các phần tử có kiểu dữ liệu float cho sô và nan(ko xác định) cho chuỗi. Tìm vị trí có giá trị
# không xác định trong mảng numpy
import numpy as np
# đọc dữ liệu
iris_2d = np.genfromtxt("iris.csv", delimiter=',', dtype="float")

# in 5 đầu tiên 
print(iris_2d[:5])
# đếm số phần tử nan
print("số lượng các phần tử có giá trị không xác định: ", npp.isnan(iris_2d).sum())

# Lấy vị trí, trả về (array_of_index, array_of_colum_index)
index = np.where(np.isnan(iris_2d))

In [2]:
# vd8: Đọc 4 cột dữ liệu đầu tiên, và lọc các dòng có petalength(cột thứ 3)>1.5 và sepallength(cột thứ 1)<5.0
import numpy as np

# đọc dữ liệu
iris_2d = np.genfromtxt("Iris.csv", delimiter=",", dtype = "float", usecols = [0,1,2,3])
# điều kieneh để lấy dữ liệu
condition = (iris_2d[:,2] > 1.5) & (iris_2d[:,0] < 5.0)
# Lấy dữ liệu
out = iris_2d[condition]
print(out)

[[1.  5.1 3.5 1.4]
 [2.  4.9 3.  1.4]
 [3.  4.7 3.2 1.3]
 [4.  4.6 3.1 1.5]]


C:\Users\MINH\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in greater
  import sys
C:\Users\MINH\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in less
  import sys


In [2]:
# vd9: Tìm mối tương quan giữa Sepallength(cột thứ 1) và Petallength(cột thứ 3)
import numpy as np

# Đọc dữ liệu 
iris_2d = np.genfromtxt("Iris.csv", delimiter=",", dtype="float", usecols=[0,1,2,3])
# C1: Dùng hàm corrcoef từ numpy 
out1 = np.corrcoef(iris_2d[:,0], iris_2d[:,2])[0,1]
print(out1)
# c2: Dùng hàm pearsonr từ scipy
from scipy.stats.stats import pearsonr
out2 = pearsonr(iris_2d[:,0], iris_2d[:,2])[0]
print(out2)

nan


ValueError: array must not contain infs or NaNs

In [4]:
# vd10: Tìm giá trị duy nhất và sô lượng các giá trị duy nhất trong cột species
import numpy as np
# đọc dữ liẹu
iris = np.genfromtxt("Iris.csv", delimiter=",", dtype="object")
# Dùng hàm unique
out = np.unique(iris[:,4], return_counts= True)
print(out)

(array([b'0.1', b'0.2', b'0.3', b'0.4', b'0.5', b'0.6', b'1.0', b'1.1',
       b'1.2', b'1.3', b'1.4', b'1.5', b'1.6', b'1.7', b'1.8', b'1.9',
       b'2.0', b'2.1', b'2.2', b'2.3', b'2.4', b'2.5', b'PetalWidthCm'],
      dtype=object), array([ 6, 28,  7,  7,  1,  1,  7,  3,  5, 13,  8, 12,  4,  2, 12,  5,  6,
        6,  3,  8,  3,  3,  1], dtype=int64))


In [5]:
# vd11: Chuyển đổi cột 3 petallength thành 3 mảng như sau
import numpy as np

# Đọc dữ liệu
iris = np.genfromtxt("Iris.csv", delimiter=",", dtype="oject")
# hàm np.digitize: trả về vị trí chỉ số của bin mà mỗi phần tử thuộc khoảng bin tương ứng
# chuyển đỗi mảng sang mảng bin tương ứng với bảng định nghĩa chuyển đôi
bin_petal_length = np.digitize(iris[:,2].astype(float), [0,3,5,10])
# ánh xạ bảng bin thành văn bản tương ứng
label_map = {1:"small", 2:"medium", 3:"large", 4:np.nan}
map_bin_petallength = [label_map[x] for x in bin_petal_length]
# in 4 phần tử đầu tiên
print(map_bin_petallength[:4])

TypeError: data type "o" not understood

In [2]:
# vd12: Tạo 1 cột mới, trong đó giá trị mỗi phần tử là: (petallength + sepal_length) / 2
import numpy as np

# Đọc dữ liệu 
iris_2d = np.genfromtxt('Iris.csv', delimiter = ',', dtype = 'object')

# Rút trích xuất cột petallength * sepal_length
sepallength = iris_2d[:,0].astype('float')
petallength = iris_2d[:,2].astype('float')
new_col = (petallength + sepallength)/2

# Định dạng cột mới cùng số chiều với iris_2d
print(new_col.shape)
new_col = new_col[:, np.newaxis]
print(new_col.shape)

# Thêm côt mới vào iris_2d dùng hàm hstack
out = np.hstack([iris_2d,new_col])
print(out.shape)

ValueError: could not convert string to float: b'Id'

In [5]:
# vd14: Tìm giá trị thứ 2 của petallength trong nhóm setosa
import numpy as np
# Đọc dữ liệu
iris = np.genfromtxt('Iris.csv',delimiter = ',', dtype='object')

# Tạo mảng mới nhóm bởi giá trị setosa
setosa = iris[iris[:,4] == b'Iris-setosa']
print(setosa.shape)

# Chỉ lấy cột 2 rồi chuyển thành kiểu float
petal_length_setosa = setosa[:,2].astype(float)

#Lấy giá trị lớn thứ 2 của mảng
out = np.unique(np.sort(petal_length_setosa))[-2]
print(out)

(0, 6)


IndexError: index -1 is out of bounds for axis 0 with size 0

In [7]:
# vd15: Sắp xếp tập dữ liệu iris dựa trên cột sepallength
import numpy as np

# Đọc dữ liệu 
iris = np.genfromtxt("Iris.csv",delimiter = ',', dtype='object')

# Sắp xếp cột 0( Sepallength)
out = iris[iris[:0,0].argsort()
print(out[:5])

SyntaxError: invalid syntax (<ipython-input-7-5b9a70f509e3>, line 9)

In [8]:
# vd15: Tìm giá trị xuất hiện nhiều nhất trong cột petallength(cột thứ 3) trong
# tập dữ liệu iris. Lấy các phần tử duy nhất và số lượng mỗi phần tử
import numpy as np

# Đọc dữ liệu
iris = np.genfromtxt("Iris.csv",delimiter=',',dtype='object')

values , counts = np.unique(iris[:2],return_counts = True)
print(values)
print(counts)

# Dùng hàm np.argmax để tìm vị trí của phần tử xuất hiện nhiều nhất
# print(values[np.argmax(counts)], np.argmax(counts))

[b'0.2' b'1' b'1.4' b'3.5' b'5.1' b'Id' b'Iris-setosa' b'PetalLengthCm'
 b'PetalWidthCm' b'SepalLengthCm' b'SepalWidthCm' b'Species']
[1 1 1 1 1 1 1 1 1 1 1 1]


In [9]:
# vd17: Tìm vị trí xuất hiện đầu tiên của 1 giá trị lớn hơn 1.0 trong cột thứ 4(petalwwidth)
import numpy as np

# đọc dữ liệu
iris = np.genfromtxt("Iris.csv", delimiter=',', dtype='object')
print(iris[:14])

# Lấy cột thứ 4 petalwidth và định dạng kiểu float thỏa mã lớn hown1.0
petalwidth = iris[:,3].astype('float') > 1.0

# Hàm argwhere lấy index của mảng thỏa mãn đk cho trc
index = np.argwhere(petalwidth)[0]
print(index)

[[b'Id' b'SepalLengthCm' b'SepalWidthCm' b'PetalLengthCm' b'PetalWidthCm'
  b'Species']
 [b'1' b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'2' b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'3' b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4' b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5' b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'6' b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'7' b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'8' b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'9' b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'10' b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'11' b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa']
 [b'12' b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'13' b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']]


ValueError: could not convert string to float: b'PetalLengthCm'

In [10]:
# vd18: Tạo 1 id nhóm dựa trên 1 biến phân loại cho trc, dùng cột species từ mảng iris/
import numpy as np

# Đọc dữ liệu
species = np.genfromtxt('iris.csv', delimiter=',',dtype='float',usecols=4)

# c1: 
output1 = [np.argwhere(np.unique(species) == s).tolist()[0][0]]
            for val in np.unique(species)
            for s in species[species == val]
print(output1)
# c2: dùng for
for val in uniqs:
#     Tìm mỗi phần tử trong mảng
    for s in species[species==val]
        groupid = np.argwher(nuiqs == s).tolist()[0][0]
        # chèn vào mảng kết quả
        output2.append(groupid)
print(output2)

IndentationError: unexpected indent (<ipython-input-10-cb3dced7c5e5>, line 9)