In [8]:
import numpy as np
array = np.array([[1,2,3,4],[5,6,7,8]])
array[array>=5]
print(array)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
#truy xuất theo cột 0
#ảnh có chiều theo thứ tự là : hight,weight,3
a=np.array([[1,2],[3,4]])
a[:,0]

array([1, 3])