In [10]:
import numpy as np
a = np.array([[[1 for _ in range(0,5)] for _ in range(0,4) ] for _ in range(0,3)])
a.shape

(3, 4, 5)

In [11]:
# Init a numpy array (Bắt đầu 1 mảng)
array = np.array([[1,2,3,4],[5,6,7,8]])

# Print out the arr it self(In các phần tử trong mảng)
print(array)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
# Print out memory address(In ra địa chỉ của bộ nhớ)
print(array.data)

In [13]:
# Print out the shape of array(In ra kiểu hình dạng của mảng(cột,hàng))
print(array.shape)

(2, 4)


In [14]:
# Print outthe the data type of array(In ra kiểu dữ liệu của mảng)
print(array.dtype)

int32


In [15]:
# Print out the stride of array(In ra giá trị mà nó bước qua)
#Vd:a[0,0]->a[0,1] là 4 bytes và for a[0,0]->a[1,0] là: 16 byte
print(array.strides)

(16, 4)


In [17]:
print("Indentity matrix:")#( Ma trận đường chéo chính )
print(np.eye(5)) #Tạo 1 ma trận vuông cấp 5 có đường chéo chính = 1

Indentity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
# Create an array of ones ( Tạo ra ma trận col:3,row:4 toàn phần tử 1)
print("Array of ones: ")
print(np.ones((3,4)))

Array of ones: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
# Create an array of zeros ( Tạo ra ma trận có col:2,row:3,hidth:4 toàn phần tử  0)
print("Array of zeros:")
print(np.zeros((2,3,4)))
print(np.zeros((2,3,4)).shape)


Array of zeros:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(2, 3, 4)


In [30]:
# Create an array with random values (Tạo mảng với 1 giá trị ngẫu nhiên)
print("Array with random values:")
print(np.random.random((2,2)))

Array with random values:
[[0.98270256 0.78100331]
 [0.18093475 0.09475161]]


In [31]:
# Create an empty array ( Tạo 1 mảng rỗng)
print(np.empty((3,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [32]:
#Create a full array (Tạo 1 mảng và ép giá trị của từng phần tử cho trước)
print(np.full((2,2),7))

[[7 7]
 [7 7]]


In [36]:
# Create an array of evenly-spaced values( Tạo 1 mảng có các giá trị cách đều nhau)
print(np.arange(10,25,5))

[10 15 20]


In [37]:
# Create an array of evenly-spaced values( Tạo 1 mảng có các giá trị cách đều nhau)
print(np.linspace(0,2,9))

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [40]:
# Create a diagonal matrix( Tạo 1 đường chéo chính cho am trận)
print(np.diag([1,4,5,6],0))

[[1 0 0 0]
 [0 4 0 0]
 [0 0 5 0]
 [0 0 0 6]]


In [43]:
# CÁC Phép Tính Trên MaTRix
#1: Cùng kích thước
x = np.ones((3,4))
print(x.shape)
y = np.random.random((3,4))
print(y.shape)
x+y

(3, 4)
(3, 4)


array([[1.28048633, 1.4302441 , 1.48633868, 1.72346122],
       [1.93863739, 1.73411788, 1.80418596, 1.80703568],
       [1.85799421, 1.42501913, 1.85771702, 1.7714584 ]])

In [45]:
#2:Hai chiều cũng tương thích khi 1 trong số chúng là 1
x = np.ones((3,4))
print(x.shape)
y=np.arange(4)
print(y.shape)
x-y
print((x-y).shape)

(3, 4)
(4,)
(3, 4)


In [48]:
#3: Các mảng chỉ có thể được phát cùng nhau nếu chúng tương thích ở tất cả ở các chiều
x = np.ones((3,4))
y = np.random.random((5,1,4))
# Add x and y
print(x+y)
print((x+y).shape)

[[[1.13415406 1.55649836 1.87029232 1.26419096]
  [1.13415406 1.55649836 1.87029232 1.26419096]
  [1.13415406 1.55649836 1.87029232 1.26419096]]

 [[1.84619773 1.71241596 1.71002803 1.66260766]
  [1.84619773 1.71241596 1.71002803 1.66260766]
  [1.84619773 1.71241596 1.71002803 1.66260766]]

 [[1.53121243 1.37405204 1.01464316 1.40831393]
  [1.53121243 1.37405204 1.01464316 1.40831393]
  [1.53121243 1.37405204 1.01464316 1.40831393]]

 [[1.50670742 1.49559238 1.5190847  1.95083482]
  [1.50670742 1.49559238 1.5190847  1.95083482]
  [1.50670742 1.49559238 1.5190847  1.95083482]]

 [[1.63653826 1.49831863 1.7101938  1.02707033]
  [1.63653826 1.49831863 1.7101938  1.02707033]
  [1.63653826 1.49831863 1.7101938  1.02707033]]]
(5, 3, 4)


In [ ]:
#4: Sử dụng các hàm trong numpy để tính toán

In [49]:
# Hàm Add( + )
x= np.ones((3,4))
y= np.ones((3,4))
np.add(x,y) # Tương tự như '+'

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [51]:
# Hàm Subtract( - )
x= np.ones((3,4))
y= np.ones((3,4))
np.subtract(x,y) # Tương tự như '-'

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
# Hàm Divide( / )
x= np.ones((3,4))
y= np.ones((3,4))
np.divide(x,y)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [57]:
# Hàm multiply( * )
x= np.ones((3,4))
y= np.ones((3,4))
np.multiply(x,y)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
# Hàm Remanider( % )
x= np.ones((3,4))
y= np.ones((3,4))
np.remainder(x,y)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
np.add(x,y)

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [61]:
# Cách sử dụng các toán tử điều kiện để truy xuất mảng 
array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [62]:
# In ra các phần tử > 5 trong mảng
# C1
b= array >5
print(b)

[[False False False False]
 [False  True  True  True]]


In [64]:
b = np.array(b,dtype=np.int64)
print(b)

[[0 0 0 0]
 [0 1 1 1]]


In [65]:
array*b

array([[0, 0, 0, 0],
       [0, 6, 7, 8]], dtype=int64)

In [67]:
# C2
print(array[array>5])
# C3
b=np.where(array>5)
print(array[b])

[6 7 8]
[6 7 8]


In [68]:
array != 5

array([[ True,  True,  True,  True],
       [False,  True,  True,  True]])

In [76]:
print(array[array!=5])
print(array[np.where(array!=5)])

[1 2 3 4 6 7 8]
[1 2 3 4 6 7 8]


In [80]:
#  Toán tử logic
a= np.array([True, True, False, False])
b= np.array([False, False, True, True])
# Toán tử AND
print(np.logical_and(a,b))
# Toán tử OR
print(np.logical_or(a,b))
# Toán tử Not
print(np.logical_not(a,b))

[False False False False]
[ True  True  True  True]
[False False  True  True]


In [82]:
# SubSet,Slice,And Index Arrays
#1: Indexing and Subsetting NumPy Array( Truy cập vào phần tử con trong mảng)
# Tạo 1 mảng bằng arange
my_array = np.arange(1,5)
my_2darray = np.arange(1,9).reshape(2,4)
my_3darray = np.arange(1,17).reshape(2,2,4)
print(my_array)
print(my_2darray)
print(my_3darray)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [86]:
# select the element at the 1st index( truy xuất vào phân tử thứ 1 trong mảng)
print(my_array[1])
# select the element at row 1 colum 2 (Truy xuất vào phần tử có hàng 1 , cột 2)
print(my_2darray[1][2])
# Select the element at row 1, colum2 and height 2
print(my_3darray[1,1,2])

2
7
15


In [87]:
# We can also use boolean mask to index the array like this: Chúng ta có thể sử dungk các toán thử so sánh để truy xuất mảng
a = np.array([-2,-1,0,1,2])
print(a[a>0])

[1 2]


In [92]:
b = np.random.randint(1,10,(3,3))
b[b==2]=0
print(b)

[[1 9 6]
 [4 0 5]
 [4 4 5]]


In [93]:
# The np.where() function also have same usage: Hàm where có cách dùng như thường
np.where(a>4)

(array([], dtype=int64),)

In [96]:
# Slicing NumPy Array 
# Select itemms at index 0 and 1 ( truy xuất phần tử từ 0 và 1 trong )
print(my_array[0:2])
# Select items at row 0 and 1, column 1( truy xuất vào phần tử hàng có phần tử 0 và 1 của hàng 1)
print(my_2darray[0:2,1])
#Select items at row 1
# This í the same á saying my 3d array[1,:,:] ( truy xuất tất cả các phần tử của hàng 1)
print(my_3darray[1,:,:])
print(my_3darray[1,...])

[1 2]
[2 6]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
array_slice_copied = my_array[1:2].copy(z)

In [97]:
#define array ( xác định 1 mảng)
data = np.array([[11,22,33],[44,55,66],[77,88,99]])
# Separate data ( Dữ liệu rời)
x,y = data[:,:-1],data[:,-1]
print("In put Features:\n",x)
print("Out put:",y)

In put Features:
 [[11 22]
 [44 55]
 [77 88]]
Out put: [33 66 99]


In [102]:
#Define array( Xác định 1  mảng)
data = np.array([[11,22,33],[44,55,66],[77,88,99]])
split = 2
train, test = data[:split, :],data[split:, :]
print("Train data:\n",data)
print("Test data:\n",test)

Train data:
 [[11 22 33]
 [44 55 66]
 [77 88 99]]
Test data:
 [[77 88 99]]


In [103]:
#Reshaping And Resizing Array (Đặt lại hình dạng và đưa mảng trở về kích thước ban đầu)
x = np.array([[[1, 1, 1, 1],
              [1, 1, 1, 1],
              [1, 1, 1, 1],
              [0, 0, 0, 0],
              [0, 0, 0, 0],
              [0, 0, 0, 0]],
             [[1, 1, 1, 1],
              [1, 1, 1, 1],
              [1, 1, 1, 1],
              [0, 0, 0, 0],
              [0, 0, 0, 0],
              [0, 0, 0, 0]]])

In [104]:
# Print the shape of x
print(x.shape)

(2, 6, 4)


In [106]:
# Resize x to ((6,4))
print(np.resize(x,(6,4)))
# Try out this as well
x.resize((6,4))
# Print out x
print(x)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [112]:
x = np.ones((3,4))
# Print the sizeof x to see what's possible
print(x.size)
# Reshape x to (2,6)
print(x.reshape(2,6))
# Flatten x
z = x.ravel()
print(z)

12
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [114]:
# Reshape Array for machine learning
# Reshape 1D to 2D
# define array
data = np.array([11,22,33,44,55])
print(data.shape)
# reshape
data = data.reshape(data.shape[0],1)
print(data.shape)
print(data)

(5,)
(5, 1)
[[11]
 [22]
 [33]
 [44]
 [55]]


In [117]:
# Reshape 2D to 3D Array
# List of data
data = [[11,22],[33,44],[55,66]]
# array of data
data = np.array(data)
print(data.shape)
# Reshape 
data = data.reshape((data.shape[0],data.shape[1],1))
print(data.shape)
print(data)

(3, 2)
(3, 2, 1)
[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]


In [118]:
# TRansposeNumpy Arrays( Ma trận chuyển vị)
print(my_2darray)
print(np.transpose(my_2darray))
print(my_2darray.T)

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [123]:
# Addtitional Shape Method
# Append a 1D array to your my_array
new_array = np.append(my_array,[7,8,9,10])
print(new_array)
# Append an extra colum to your my_2darray
new_2darray = np.append(my_2darray,[[7],[8]],axis = 1)
# Print new_2d_array
print(new_2darray)

[ 1  2  3  4  7  8  9 10]
[[1 2 3 4 7]
 [5 6 7 8 8]]


In [125]:
# Insert And Delete Element
# Insert 5 at index 1
np.insert(my_array,1,5)
# Delete the values at index 1
np.delete(my_array,[1])

array([1, 3, 4])

In [131]:
# Join And Split Arrays ( gop va tach mang)
x = np.ones(4)
print(x)
print(x.ndim)
my_array = np.arange(1,5)
print(my_array)
print(my_array.ndim)
my_resized_array = np.resize(np.arange(1,5),(2,4))
my_2d_array = np.arange(1,9).reshape(2,4)

[1. 1. 1. 1.]
1
[1 2 3 4]
1


In [134]:
# Concatrntate my array and x
print(np.concatenate((my_array,x)))

[1. 2. 3. 4. 1. 1. 1. 1.]


In [136]:
# Stack arrays row-wise
print(np.vstack((my_array, my_2d_array)))
            

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]


In [137]:
# Stack arrays row_wise
print(np.r_[my_resized_array, my_2d_array])

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]


In [138]:
# Stack arrays horizontally
print(np.hstack((my_resized_array, my_2d_array)))

[[1 2 3 4 1 2 3 4]
 [1 2 3 4 5 6 7 8]]


In [139]:
# Stack arrays colum-wise
print(np.column_stack((my_resized_array, my_2d_array)))

[[1 2 3 4 1 2 3 4]
 [1 2 3 4 5 6 7 8]]


In [140]:
# Stack arrays column-wise
print(np.c_[my_resized_array, my_2d_array])

[[1 2 3 4 1 2 3 4]
 [1 2 3 4 5 6 7 8]]


In [143]:
my_stacked_array = np.array([[1,2,3,4,1,2,3,4,],
                             [1,2,3,4,5,6,7,8]])
# Split my_stacked_array horizontally at the 2nd index
print(np.hsplit(my_stacked_array,2))
# Split my_stacked_array vertically at the 2nd index
print(np.vsplit(my_stacked_array,2))

[array([[1, 2, 3, 4],
       [1, 2, 3, 4]]), array([[1, 2, 3, 4],
       [5, 6, 7, 8]])]
[array([[1, 2, 3, 4, 1, 2, 3, 4]]), array([[1, 2, 3, 4, 5, 6, 7, 8]])]


In [2]:
a = np.random.randit(5)
print(a)
print(np.sort(a))
a = np.random.randit(a)
print(a)
print(np.agsort(a))

NameError: name 'np' is not defined